# Generated by Django 4.0.1 on 2022-01-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoTestApplication', '0002_movie_critic_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
