# Generated by Django 4.0.1 on 2022-01-27 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoTestApplication', '0005_movie_critic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
