# Generated by Django 4.0.1 on 2022-01-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoTestApplication', '0007_moviecritic_rename_critic_movie_sinopsis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecritic',
            name='created_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
